// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6yJ5ETdi_YcgGNAc6AJXYzQMk-_rm1VM',
    appId: '1:687271158294:web:ea935dfc5aa1fc54b7cb37',
    messagingSenderId: '687271158294',
    projectId: 'newsapp-5b819',
    authDomain: 'newsapp-5b819.firebaseapp.com',
    storageBucket: 'newsapp-5b819.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1vpyIgL7EdsBPvEurXluu8nBBOAGkCKI',
    appId: '1:687271158294:android:91ec772fbd15131cb7cb37',
    messagingSenderId: '687271158294',
    projectId: 'newsapp-5b819',
    storageBucket: 'newsapp-5b819.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOmhsvUVKDSTyUEGCG7gztoKdt9eqr5gA',
    appId: '1:687271158294:ios:108fca18f537e076b7cb37',
    messagingSenderId: '687271158294',
    projectId: 'newsapp-5b819',
    storageBucket: 'newsapp-5b819.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOmhsvUVKDSTyUEGCG7gztoKdt9eqr5gA',
    appId: '1:687271158294:ios:108fca18f537e076b7cb37',
    messagingSenderId: '687271158294',
    projectId: 'newsapp-5b819',
    storageBucket: 'newsapp-5b819.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );
}
